name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: cbeloni
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: danielr1996/envsubst-action@1.0.0
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        with:
          input: .env.template
          output: .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: cbeloni/setlistclub-front:amd64

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_MGC }}" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_MGC }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f argocd-mgc/setlistclub-front-mgc.yaml --insecure-skip-tls-verify
          kubectl rollout restart deployment/setlistclub-front --insecure-skip-tls-verify

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
